#!/usr/bin/env python3
"""
gen_import_table.py — emit src/import_table.cpp for the DuckTales port.

PS3 firmware EBOOTs resolve imports through a function-pointer table in the
data segment. Each imported function has a tiny stub thunk (lifted as
func_00BDxxxx) that does:

    r12 = *(SLOT)          ; SLOT in the data segment, e.g. 0xCF37FC
    ... -> bctr through *(r12)  ; r12 points to an OPD {entry, toc}

In the *unpatched* static ELF every SLOT is a self-referential placeholder
(SLOT -> its own thunk) that the real PS3 PRX loader overwrites at load time.
We do the loader's job at init: for each import we synthesize an OPD whose
entry is a unique sentinel guest address, repoint the SLOT at that OPD, and
register the sentinel in the indirect-dispatch table so it routes into the
HLE NID dispatcher.

The SLOT address for each stub is recovered by parsing the lifted thunk body
(the `vm_read32(ctx->gpr[12] + 0xNNNN)` with the `0xCF << 16` base load).

Inputs:
  - analysis/EBOOT.imports.json   [{library, nid, stub}]   (from ppu_loader.py)
  - src/recomp/ppu_recomp_*.cpp   (lifted thunks, for stub -> slot)
  - ps3recomp tools/nid_database  (NID -> human name)

Output:
  - src/import_table.cpp
"""
import json, glob, re, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
PORT = os.path.dirname(HERE)                      # ducktales/
PS3  = os.path.normpath(os.path.join(PORT, "..", "..", "ps3"))
sys.path.insert(0, os.path.join(PS3, "tools"))

DATA_SEG_BASE = 0x00CF0000   # matches the `0xCF << 16` base in the thunks

def load_imports():
    f = glob.glob(os.path.join(PORT, "analysis", "*.imports.json"))
    if not f:
        sys.exit("no analysis/*.imports.json — run tools/ppu_loader.py first")
    return json.load(open(f[0]))

def build_slot_map():
    """stub_va -> slot_va, parsed from the lifted thunk bodies."""
    slot = {}
    pat = re.compile(
        r'void (func_00BD[0-9A-F]{4})\(ppu_context\* ctx\) \{(.*?)\n\}', re.S)
    off = re.compile(r'vm_read32\(ctx->gpr\[12\] \+ 0x([0-9A-Fa-f]+)\)')
    for cf in glob.glob(os.path.join(PORT, "src", "recomp", "ppu_recomp_*.cpp")):
        t = open(cf, encoding="utf-8", errors="ignore").read()
        for m in pat.finditer(t):
            body = m.group(2)
            mm = off.search(body)
            if mm and "0xCF << 16" in body:
                stub_va = int(m.group(1).replace("func_", ""), 16)
                slot[stub_va] = DATA_SEG_BASE + int(mm.group(1), 16)
    return slot

def resolve_names(imps):
    try:
        from nid_database import get_default_db
        db = get_default_db()
    except Exception as e:
        sys.stderr.write(f"[warn] nid_database unavailable ({e}); using lib+nid names\n")
        db = None
    names = {}
    for im in imps:
        nid = int(im["nid"], 16)
        nm = None
        if db is not None:
            r = db.lookup_nid(nid)
            if r:
                nm = r[1]
        names[nid] = nm or f'{im["library"]}_{nid:08x}'
    return names

def main():
    imps = load_imports()
    slotmap = build_slot_map()
    names = resolve_names(imps)

    rows = []
    missing = 0
    for im in imps:
        stub = int(im["stub"], 16)
        nid  = int(im["nid"], 16)
        slot = slotmap.get(stub)
        if slot is None:
            missing += 1
            continue
        rows.append((slot, nid, im["library"], names[nid]))

    rows.sort()
    named = sum(1 for r in rows if not r[3].endswith(f'{r[1]:08x}'))

    out = []
    w = out.append
    w("/* Auto-generated by tools/gen_import_table.py — do not edit by hand. */")
    w("/*")
    w(" * PS3 firmware import table: repoint each data-segment slot at a")
    w(" * synthesized OPD whose entry is a sentinel routed to HLE NID dispatch.")
    w(f" * {len(rows)} imports across {len(set(r[2] for r in rows))} libraries"
      f" ({named} NID-named).")
    w(" */")
    w('#include <stdint.h>')
    w('#include <stdio.h>')
    w("")
    w('extern "C" void  vm_write32(uint64_t addr, uint32_t val);')
    w("")
    w("typedef struct { uint32_t slot_va; uint32_t nid; const char* lib; const char* name; } DuckImport;")
    w("")
    w('extern "C" const DuckImport g_duck_imports[] = {')
    for slot, nid, lib, nm in rows:
        w(f'    {{ 0x{slot:08X}u, 0x{nid:08X}u, "{lib}", "{nm}" }},')
    w("};")
    w(f"extern \"C\" const uint32_t g_duck_import_count = {len(rows)};")
    w("")
    w("/* Sentinel guest-address base: a region the game never executes from.")
    w(" * sentinel_i = SENTINEL_BASE + i; the i-th import's OPD lives at")
    w(" * OPD_BASE + i*8. Both sit in committed scratch above the heap. */")
    w("#define DUCK_SENTINEL_BASE 0x3F000000u")
    w("#define DUCK_OPD_BASE      0x3E000000u")
    w("")
    w('extern "C" uint32_t duck_import_nid_for_sentinel(uint32_t sentinel) {')
    w("    uint32_t i = sentinel - DUCK_SENTINEL_BASE;")
    w("    if (i < g_duck_import_count) return g_duck_imports[i].nid;")
    w("    return 0;")
    w("}")
    w('extern "C" const char* duck_import_name_for_sentinel(uint32_t sentinel) {')
    w("    uint32_t i = sentinel - DUCK_SENTINEL_BASE;")
    w("    if (i < g_duck_import_count) return g_duck_imports[i].name;")
    w('    return "?";')
    w("}")
    w("")
    w("/* Install the import table: synthesize an OPD per import and repoint its")
    w("   data-segment slot at it. Sentinels are resolved by an O(1) range check")
    w("   in ps3_indirect_call (not the hash table). Call AFTER elf_load_segments")
    w("   (slots live in the data seg). */")
    w('extern "C" void duck_install_imports(void) {')
    w("    for (uint32_t i = 0; i < g_duck_import_count; i++) {")
    w("        uint32_t opd      = DUCK_OPD_BASE + i * 8;")
    w("        uint32_t sentinel = DUCK_SENTINEL_BASE + i;")
    w("        vm_write32(opd + 0, sentinel);             /* OPD.entry */")
    w("        vm_write32(opd + 4, 0);                    /* OPD.toc   */")
    w("        vm_write32(g_duck_imports[i].slot_va, opd);/* slot -> OPD */")
    w("    }")
    w('    fprintf(stderr, "[import] installed %u firmware imports\\n", g_duck_import_count);')
    w("}")
    w("")

    dst = os.path.join(PORT, "src", "import_table.cpp")
    open(dst, "w", encoding="utf-8").write("\n".join(out))
    print(f"wrote {dst}")
    print(f"  imports mapped : {len(rows)}")
    print(f"  NID-named      : {named}/{len(rows)}")
    if missing:
        print(f"  WARNING: {missing} stubs had no parseable slot (skipped)")

if __name__ == "__main__":
    main()
